### ISSUE TITLE
Review & Modifications

### ISSUE THREAD

**Issue by Vignesh1115** [ankit1ank/AlienRegistration#1]
We would expect you to make the code extensible so that it is easy to **plug in** a new format and the application now automatically, has the capability to export to the new format without making **any changes to the application code**.

Example - Google does not make changes to Chrome each time a new browser plugin is published. The plugin effectively provides new capability without changing any code.

In our case consider we are adding a thousand new plugins, how feasible would the conditional statements currently being used be in that scenario.

**Comment by goelankitt** [comment]
The issue has been fixed. :)

**Comment by Vignesh1115** [comment]
1) The changes you have made expect the user of the application to know the formats beforehand. You have attempted to solve the first part of the problem statement. Suppose if we extend your application to a hundred formats wouldn't it be convenient if the user could be informed of what formats are currently supported by your application and then prompt them for a choice.
2) Your application has quite a lot of repetitions. 
3) The code in inconsistent with generally followed programming styles irrespective of swift specific programming style. Example: The problem with using file names like pdf.swift is that it's not possible to infer the purpose of the file by its name without looking at its contents. It is possible to make your code as descriptive as possible.

Currently the issue is still not fixed.

**Comment by goelankitt** [comment]
I have updated the code. Waiting for review.

**Comment by Vignesh1115** [comment]
There is still an issue in module.swift  selectFormat() function. Addition of a new format still requires changes to this function. Ideally it should be detected automatically. I will be closing this issue unless any further suggestions or modification is required/requested.
