### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by Vignesh1115** [ankit1ank/AlienRegistration#2]
1) Consider a situation where we might want to take the details of multiple aliens and then finally decide if the details have to be exported to any format or none at all. Would your current code be able to handle it?
2) Consider a situation where we want the blood color of the alien in Hexadecimal value only in the PDF file or CMYK value in the Text file. Could we do that currently?
You could review Part A once more and get back to us if you need any further clarifications?

**Comment by goelankitt** [comment]
Please review the code again. Hopefully the changes that I have made are able to handle your concerns.

**Comment by Vignesh1115** [comment]
1) Can the current version of the application be able to collect the details of about ten aliens continuously and then have it exported to no format at all?
2) The presentation of data according to file specific formats could be improved.
The current code resolves none of the issues we have mentioned. Could you review the application again and get back to us if you need clarifications.
